### ISSUE TITLE
Add support for ZBPLM

### ISSUE THREAD

**Issue by brgavino** [Smartenit/smartthings-devicehandlers#3]
Would it be possible to add support in the smartthings device handlers for the ZBPLM?

**Comment by thewall7** [comment]
ZBPLM is an interface for controlling Zigbee, Insteon and X10 devices. It would require a physical USB connection with the Smartthings hub. What is the intended purpose for this request?

**Comment by brgavino** [comment]
I was under the impression through some documentation that ZBPLM can translate ZigBee messages into X10/Insteon messages. A ZigBee relay, through SmartThings, would not require a USB connection (which SmartThings Hub won't provide anyways). At the very least, a ZigBee interface through ZBPLM interface would allow control of ZigBee devices through the ZBPLM. What are your thoughts on this? Thanks!

**Comment by thewall7** [comment]
Sorry for the late reply here (since we continued our conversation via email). ZBPLM is an interface and it does not convert the messages from Zigbee to Insteon/X10 or vice-versa. 
So I don't think this idea of interfacing the ZBPLM with Smartthings will work. Reason is that ZBPLM is an interface that is controlled via serial API and for it to work with Smartthings it needs a USB connection directly to the hub. Also, the Smartthings hub already has a built in zigbee radio so the Zigbee radio within ZBPLM is unnecessary/redundant, and the remaining functionality is related to Insteon and X10 for which it would be better to use a Dual-band PLM from Smartlabs IMHO (and I think there are some threads on Smartthings community about Insteon support, if that's what you are looking for). 
Let me know if I misunderstood your idea or if you have any other questions.

**Comment by thewall7** [comment]
Not an issue.
